# Generated by Django 4.2.18 on 2025-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(upload_to='research_papers/')),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('short_video', models.URLField(blank=True, null=True)),
                ('long_video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
